(function(){
  function F(v){return Number(v)||0}
  function esc2(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
  function baseFor(f){return f.baseQty!=null&&F(f.baseQty)>0?F(f.baseQty):((f.unit==='g'||f.unit==='ml')?100:1)}
  function unitFor(f){return f.unit||'g'}
  window.foodForm=function(i){
    const editing=i>=0, old=editing?day().foods[i]:null;
    const f=editing?old:{name:'',qty:100,unit:'g',cal:0,p:0,c:0,fat:0};
    window._selectedSaved=null;
    openModal(`<div class="row"><div><span class="eyebrow">FOOD LOG</span><div class="title">${editing?'Edit food':'Add food'}</div></div><button class="btn secondary small" onclick="closeModal()">Close</button></div><div class="field" style="position:relative"><label>Food name</label><input id="foodName" class="input" autocomplete="off" value="${esc2(f.name)}" oninput="suggestFood2(this.value)"><div id="suggestions"></div></div><div class="grid2"><div class="field"><label>Quantity</label><input id="foodQty" class="input" type="number" min="0" step=".1" value="${F(f.qty)||1}" oninput="recalcFood()"></div><div class="field"><label>Unit</label><input id="foodUnit" class="input" value="${esc2(f.unit||'g')}"></div></div><div class="grid2"><div class="field"><label>Calories</label><input id="foodCal" class="input" type="number" step=".1" value="${F(f.cal)}"></div><div class="field"><label>Protein g</label><input id="foodP" class="input" type="number" step=".1" value="${F(f.p)}"></div><div class="field"><label>Carbs g</label><input id="foodC" class="input" type="number" step=".1" value="${F(f.c)}"></div><div class="field"><label>Fat g</label><input id="foodFat" class="input" type="number" step=".1" value="${F(f.fat)}"></div></div><div class="muted" id="foodBaseNote">${editing?`Base: ${baseFor(f)} ${unitFor(f)}`:'Choose a saved food to automatically calculate nutrition, or enter it manually.'}</div><button class="btn" style="width:100%;margin-top:12px" onclick="saveFoodFixed(${i})">Save food</button>${editing?`<button class="btn danger" style="width:100%;margin-top:8px" onclick="removeFood(${i})">Delete</button>`:''}`);
    if(editing){const base=baseFor(f),qty=F(f.qty)||base;window._selectedSaved={name:f.name,baseQty:base,unit:unitFor(f),cal:F(f.cal)/qty*base,p:F(f.p)/qty*base,c:F(f.c)/qty*base,fat:F(f.fat)/qty*base};}
  };
  window.suggestFood2=function(q){const box=document.getElementById('suggestions');if(!box)return;const term=q.trim().toLowerCase();const matches=term.length>=2?S.foods.filter(f=>String(f.name||'').toLowerCase().includes(term)).slice(0,6):[];box.innerHTML=matches.map(f=>`<button type="button" class="quick" style="display:block;width:100%;text-align:left;margin-top:4px" onclick="selectSavedFood(${S.foods.indexOf(f)})">${esc2(f.name)} · ${baseFor(f)} ${esc2(unitFor(f))} · ${F(f.cal)} kcal</button>`).join('')};
  window.selectSavedFood=function(i){const f=S.foods[i];if(!f)return;const base=baseFor(f);window._selectedSaved={...f,baseQty:base};foodName.value=f.name;foodUnit.value=unitFor(f);foodQty.value=base;document.getElementById('suggestions').innerHTML='';recalcFood()};
  window.recalcFood=function(){const f=window._selectedSaved;if(!f)return;const base=baseFor(f),q=Math.max(0,F(foodQty.value)),mult=base?q/base:0;foodCal.value=(F(f.cal)*mult).toFixed(1);foodP.value=(F(f.p)*mult).toFixed(1);foodC.value=(F(f.c)*mult).toFixed(1);foodFat.value=(F(f.fat)*mult).toFixed(1);document.getElementById('foodBaseNote').textContent=`Base: ${base} ${unitFor(f)} = ${F(f.cal)} kcal · quantity ${q} ${unitFor(f)}`};
  window.saveFoodFixed=function(i){const name=foodName.value.trim()||'Food',qty=F(foodQty.value),unit=foodUnit.value||'g',cal=F(foodCal.value),p=F(foodP.value),c=F(foodC.value),fat=F(foodFat.value);const base=window._selectedSaved?baseFor(window._selectedSaved):qty||1;const f={name,qty,unit,cal,p,c,fat,baseQty:base};if(i<0)day().foods.push(f);else day().foods[i]=f;save();closeModal();render()};
})();